
package View;


public class Conductor extends javax.swing.JFrame {

   int xMouse,yMouse;
    public Conductor() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreyapellidos = new javax.swing.JTextPane();
        numeroconductor = new javax.swing.JTextPane();
        nombredeempresa = new javax.swing.JTextPane();
        edad = new javax.swing.JTextPane();
        identificacion = new javax.swing.JTextPane();
        bus = new javax.swing.JTextPane();
        ruta = new javax.swing.JTextPane();
        horadesalida = new javax.swing.JTextPane();
        horadesentrada = new javax.swing.JTextPane();
        recorrido = new javax.swing.JTextPane();
        guardar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        fotodecon = new javax.swing.JTextPane();
        fondoL = new javax.swing.JLabel();
        CURSOR = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreyapellidos.setBackground(new java.awt.Color(255, 255, 255));
        nombreyapellidos.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        nombreyapellidos.setForeground(new java.awt.Color(0, 0, 0));
        nombreyapellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreyapellidos.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(nombreyapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 190, 20));

        numeroconductor.setBackground(new java.awt.Color(255, 255, 255));
        numeroconductor.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        numeroconductor.setForeground(new java.awt.Color(0, 0, 0));
        numeroconductor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numeroconductor.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(numeroconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 80, 30));

        nombredeempresa.setBackground(new java.awt.Color(255, 255, 255));
        nombredeempresa.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        nombredeempresa.setForeground(new java.awt.Color(0, 0, 0));
        nombredeempresa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombredeempresa.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(nombredeempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 30));

        edad.setBackground(new java.awt.Color(255, 255, 255));
        edad.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        edad.setForeground(new java.awt.Color(0, 0, 0));
        edad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edad.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 190, 20));

        identificacion.setBackground(new java.awt.Color(255, 255, 255));
        identificacion.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        identificacion.setForeground(new java.awt.Color(0, 0, 0));
        identificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        identificacion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 190, 20));

        bus.setBackground(new java.awt.Color(255, 255, 255));
        bus.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        bus.setForeground(new java.awt.Color(0, 0, 0));
        bus.setToolTipText("");
        bus.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bus.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, 30));

        ruta.setBackground(new java.awt.Color(255, 255, 255));
        ruta.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        ruta.setForeground(new java.awt.Color(0, 0, 0));
        ruta.setToolTipText("");
        ruta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ruta.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 130, 30));

        horadesalida.setBackground(new java.awt.Color(255, 255, 255));
        horadesalida.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        horadesalida.setForeground(new java.awt.Color(0, 0, 0));
        horadesalida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        horadesalida.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(horadesalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 220, 20));

        horadesentrada.setBackground(new java.awt.Color(255, 255, 255));
        horadesentrada.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        horadesentrada.setForeground(new java.awt.Color(0, 0, 0));
        horadesentrada.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        horadesentrada.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(horadesentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 220, 20));

        recorrido.setBackground(new java.awt.Color(255, 255, 255));
        recorrido.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        recorrido.setForeground(new java.awt.Color(0, 0, 0));
        recorrido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        recorrido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(recorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 220, 20));

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GUARDAR.png"))); // NOI18N
        guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 80, -1));

        regresar.setBackground(new java.awt.Color(255, 255, 255));
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/REGRESAR.png"))); // NOI18N
        regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        fotodecon.setBackground(new java.awt.Color(255, 255, 255));
        fotodecon.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        fotodecon.setForeground(new java.awt.Color(0, 0, 0));
        fotodecon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fotodecon.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(fotodecon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 130));

        fondoL.setBackground(new java.awt.Color(255, 255, 255));
        fondoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Conductor.png"))); // NOI18N
        fondoL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(fondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 620, 540));

        CURSOR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CURSORMouseDragged(evt);
            }
        });
        CURSOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CURSORMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CURSORMousePressed(evt);
            }
        });
        jPanel1.add(CURSOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CURSORMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_CURSORMouseDragged

    private void CURSORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMouseClicked

    }//GEN-LAST:event_CURSORMouseClicked

    private void CURSORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
        

    }//GEN-LAST:event_CURSORMousePressed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Login re = new Login();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CURSOR;
    private javax.swing.JTextPane bus;
    private javax.swing.JTextPane edad;
    private javax.swing.JLabel fondoL;
    private javax.swing.JTextPane fotodecon;
    private javax.swing.JButton guardar;
    private javax.swing.JTextPane horadesalida;
    private javax.swing.JTextPane horadesentrada;
    private javax.swing.JTextPane identificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane nombredeempresa;
    private javax.swing.JTextPane nombreyapellidos;
    private javax.swing.JTextPane numeroconductor;
    private javax.swing.JTextPane recorrido;
    private javax.swing.JButton regresar;
    private javax.swing.JTextPane ruta;
    // End of variables declaration//GEN-END:variables
}
